version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ../docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql # Create database for Orthanc
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - postgres-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  orthanc:
    image: brianzhouzc/orthanc-tmi:latest
    entrypoint: ['Orthanc', '--verbose']
    container_name: orthanc-server
    restart: always
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - ../docker/orthanc/plugins:/usr/share/orthanc/plugins
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=TMI
      - ASAN_OPTIONS=verify_asan_link_order=0
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

secrets:
  orthanc.json:
    file: ../docker/orthanc/orthanc.json