version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      #  WARNING: FOR WSL USE THE FOLLOWING LINE INSTEAD:
      #- ~/docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql # Create databases for Orthanc and OrthancToolsJS
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - postgres-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  orthanc:
    image: brianzhouzc/orthanc-tmi-plugins:latest
    entrypoint: ['Orthanc']#, '--verbose']
    container_name: orthanc-server
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      #  WARNING: FOR WSL USE THE FOLLOWING LINE INSTEAD:
      #- ~/docker/orthanc/db:/var/lib/orthanc/db
      - ./docker/orthanc/db:/var/lib/orthanc/db
      - ./docker/orthanc/storage:/var/lib/orthanc/dicom
      - ./docker/orthanc/plugins:/usr/share/orthanc/plugins
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=TMI
    networks:
      - postgres-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-network

  orthanctoolsjs:
    image: salimkanoun/orthanctoolsjs
    container_name: orthanctoolsjs
    restart: unless-stopped
    volumes:
      - ./docker/orthanc/orthanctoolsjs:/OrthancToolsJs/data:Z
    environment:
      TZ: "America/Vancouver"
      ORTHANC_ADDRESS: "http://orthanc"
      ORTHANC_PORT: "8042"
      ORTHANC_USERNAME: "orthanc"
      ORTHANC_PASSWORD: "orthanc"
      DOMAIN_PROTOCOL: "https"
      DOMAIN_ADDRESS: "0e44be91-4285-440b-a132-c6580851eed7.pub.instances.scw.cloud"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      DB_USERNAME: "postgres"
      DB_PASSWORD: "example"
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_NAME: orthanctoolsjs
    networks:
      - postgres-network

  redis:
    image: redis:alpine
    networks:
      - postgres-network

  orthanctoolsjspacs:
    image: brianzhouzc/orthanc-tmi-plugins:latest
    ports: ["8043:8042"]
    container_name: orthanctoolsjspacs
    restart: unless-stopped
    volumes:
      - ./docker/orthanc/orthancpacs:/var/lib/orthanc/db:Z
    networks:
      - postgres-network
    environment:
      ORTHANC__NAME: "OrthancPacs"
      ORTHANC__DICOM_MODALITIES_IN_DATABASE: "true"
      ORTHANC__REGISTERED_USERS: |
        {"orthanc": "orthanc"}

networks:
  postgres-network:
    driver: bridge

secrets:
  orthanc.json:
    file: ./docker/orthanc/orthanc.json
