version: 2.1

jobs:
  google-test:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Environment Setup
          command: |
            git submodule init
            git submodule update
            sudo apt-get install gcc
            sudo apt purge --auto-remove cmake
            sudo apt update && \
            sudo apt install -y software-properties-common lsb-release && \
            sudo apt clean all
            wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
            sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
            sudo apt update
            sudo apt install kitware-archive-keyring
            sudo rm /etc/apt/trusted.gpg.d/kitware.gpg
            sudo apt update
            sudo apt install cmake
            sudo apt-get install wget ca-certificates
            wget --no-check-certificate --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
            sudo apt-get update
            sudo apt-get install postgresql postgresql-contrib
            sudo apt-get install libpq5
            sudo apt-get install libpq-dev
            echo 'Environment setup complete'
      - run:
          name: Build with CMake
          command: |
            mkdir build
            cd build
            cmake ..
            make
            echo 'Build complete'
      - run:
          name: Run googletest suite
          command: |
            cd build
            ./build/all-tests --gtest_output=xml:build/
      - store_test_results:
          path: ./build


workflows:
  version: 2
  GoogleTest:
    jobs:
      - google-test