version: 2.1

jobs:
  test:
    docker:
      - image: silverlinings89/cpp_build_environment:latest 
    steps:
      - checkout
      - run:
          name: Setup gtest child repo
          command: |
            git submodule init
            git submodule update 
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir build
            cd build
            cmake ..
            make
      - run:
          name: Execute Tests
          command: |
            cd build
            ./Orthanc-TMI-tests --gtest_output=xml
      - store_test_results:
          path: build

  workflows:
    version: 2
    GoogleTest:
      jobs:
        - test
        