version: 2.1

jobs:
  google-test:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Environment Setup
          command: |
            sudo snap refresh
            sudo apt-get install gcc
            sudo apt purge --auto-remove cmake
            sudo snap install cmake --classic
            echo 'Environment setup complete'

      - run:
          name: Build with CMake
          command: |
            mkdir build
            cd build
            cmake ..
            make
            echo 'Build complete'
          
      - run:
          name: Run googletest suite
          command: |
            ./Orthanc-TMI-tests
            echo 'Tests run complete'

workflows:
  version: 2
  GoogleTest:
    jobs:
      - google-test