version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - run:
          name: Environment Setup
          command: |
            sudo apt-get install gcc
            sudo apt-get install cmake
            echo 'Environment setup complete'
  google-test:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Environment Setup
          command: |
            sudo apt-get install gcc
            sudo apt purge --auto-remove cmake
            sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null --allow
            sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
            sudo apt update --allow
            sudo apt install cmake --allow
            echo 'Environment setup complete'

      - run:
          name: Build with CMake
          command: |
            mkdir build
            cd build
            cmake ..
            make
            echo 'Build complete'
          
      - run:
          name: Run googletest suite
          command: |
            ./Orthanc-TMI-tests
            echo 'Tests run complete'

workflows:
  version: 2
  GoogleTest:
    jobs:
      - build
      - google-test