  on:
    pull_request:
      branches:
        - master
        - develop

  env:
    BUILD_TYPE: Debug

  jobs:
    Google_Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Clone Orthanc-TMI
          uses: actions/checkout@v2
          with:
            submodules: true
        - name: Install dependencies
          run: |
            sudo apt install -y software-properties-common lsb-release
            sudo apt-get install \
              gcc \
              ninja-build \
              cmake \
              postgresql \
              postgresql-contrib \
              libpq5 \
              libpq-dev
        - name: Build
          run: |
            cmake \
              -S . \
              -B build \
              -G Ninja
            ninja -C build
        - name: Prepare test environment
          run: |
            docker-compose up
        - name: Run tests
          run: |
            if sudo docker ps --all --filter name=orthanc-server --format '{{.Status}}' | grep Up; then : else throw "Orthanc failed to start, probably couldn't load the plugin"; fi
            build/bin/all-tests --gtest_output=xml:build/
