  on:
    pull_request:
      branches:
        - master
        - develop
        - libraries

  env:
    BUILD_TYPE: Debug

  jobs:
    Google_Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Clone Orthanc-TMI
          uses: actions/checkout@v2
          with:
            submodules: true
        - name: Install dependencies
          run: |
            sudo apt install -y software-properties-common lsb-release
            sudo apt-get install \
              gcc \
              ninja-build \
              cmake \
              postgresql \
              postgresql-contrib \
              libpq5 \
              libpq-dev
        - name: Build
          run: |
            cmake \
              -S . \
              -B build \
              -G Ninja
            ninja -C build DataAnonymizer
            ninja -C build all-tests
        - name: Prepare test environment
          run: |
            docker-compose up -d && sleep 10s
        - name: Run tests
          run: |
            status=$(docker ps --all --filter name=orthanc-server --format '{{.Status}}')
            echo $status
            if echo $status | grep Up &>/dev/null; then :; else exit 1; fi
            build/bin/all-tests --gtest_output=xml:build/
